name = "kv-worker"
compatibility_date = "2023-12-01"

main = "src/index.ts"
minify = true

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "MY_KV"
id = "ddba7f05e8b9406782831c91c879277e"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
