name: Cloudflare Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - new
    paths:
      - "cloudflare/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: KV Worker Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: "cloudflare/kv-worker"
